version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '8080:8080'
    environment:
      - VITE_API_HOST=api
      - VITE_API_PORT=3001
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '3001:3001'
    volumes:
      - ./server/db:/app/db
