version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        VITE_API_URL: http://api:3001
    ports:
      - "8080:8080"
    depends_on:
      - api

  api:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server/db:/app/db
