version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      VITE_API_URL: http://backend:3001
    depends_on:
      - api

  api:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server/db:/app/db
